# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Pavel/workspace/White-Albatross/GhastlyLion/GhastlyLion.ui'
#
# Created: Sun Aug 16 10:37:51 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_GhastlyLion(object):
    def setupUi(self, GhastlyLion):
        GhastlyLion.setObjectName("GhastlyLion")
        GhastlyLion.resize(1145, 886)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/main/lion.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GhastlyLion.setWindowIcon(icon)
        self.verticalLayout_5 = QtGui.QVBoxLayout(GhastlyLion)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.splitter = QtGui.QSplitter(GhastlyLion)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox_2 = QtGui.QGroupBox(self.splitter)
        self.groupBox_2.setBaseSize(QtCore.QSize(0, 0))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.imagesList = QtGui.QListWidget(self.groupBox_2)
        self.imagesList.setObjectName("imagesList")
        self.verticalLayout.addWidget(self.imagesList)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addImages = QtGui.QPushButton(self.groupBox_2)
        self.addImages.setWhatsThis("")
        self.addImages.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/main/ajouter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addImages.setIcon(icon1)
        self.addImages.setIconSize(QtCore.QSize(64, 64))
        self.addImages.setObjectName("addImages")
        self.horizontalLayout_2.addWidget(self.addImages)
        self.openFolder = QtGui.QPushButton(self.groupBox_2)
        self.openFolder.setWhatsThis("")
        self.openFolder.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/main/dossierbleu_download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openFolder.setIcon(icon2)
        self.openFolder.setIconSize(QtCore.QSize(64, 64))
        self.openFolder.setObjectName("openFolder")
        self.horizontalLayout_2.addWidget(self.openFolder)
        self.removeImages = QtGui.QPushButton(self.groupBox_2)
        self.removeImages.setEnabled(False)
        self.removeImages.setWhatsThis("")
        self.removeImages.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/main/supprimer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeImages.setIcon(icon3)
        self.removeImages.setIconSize(QtCore.QSize(64, 64))
        self.removeImages.setObjectName("removeImages")
        self.horizontalLayout_2.addWidget(self.removeImages)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayoutWidget = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.workLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.workLayout.setContentsMargins(0, 0, 0, 0)
        self.workLayout.setObjectName("workLayout")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox = QtGui.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save = QtGui.QPushButton(self.groupBox)
        self.save.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/main/floppy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save.setIcon(icon4)
        self.save.setIconSize(QtCore.QSize(64, 64))
        self.save.setObjectName("save")
        self.horizontalLayout.addWidget(self.save)
        spacerItem1 = QtGui.QSpacerItem(218, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.workLayout.addLayout(self.horizontalLayout_4)
        self.widget = QtGui.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_3 = QtGui.QGroupBox(self.widget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.type = QtGui.QComboBox(self.groupBox_3)
        self.type.setObjectName("type")
        self.type.addItem("")
        self.type.addItem("")
        self.type.addItem("")
        self.verticalLayout_2.addWidget(self.type)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.widget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.figures = QtGui.QListWidget(self.groupBox_4)
        self.figures.setObjectName("figures")
        self.verticalLayout_3.addWidget(self.figures)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_4 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_4.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/main/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon5)
        self.pushButton_4.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.pushButton_5 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_5.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/main/moins.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon6)
        self.pushButton_5.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.verticalLayout_5.addWidget(self.splitter)

        self.retranslateUi(GhastlyLion)
        QtCore.QMetaObject.connectSlotsByName(GhastlyLion)

    def retranslateUi(self, GhastlyLion):
        GhastlyLion.setWindowTitle(QtGui.QApplication.translate("GhastlyLion", "Жуткий лев - рисователь физических форм для Box2D", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("GhastlyLion", "Файлы", None, QtGui.QApplication.UnicodeUTF8))
        self.addImages.setToolTip(QtGui.QApplication.translate("GhastlyLion", "Добавить файлы", None, QtGui.QApplication.UnicodeUTF8))
        self.openFolder.setToolTip(QtGui.QApplication.translate("GhastlyLion", "Открыть директорию", None, QtGui.QApplication.UnicodeUTF8))
        self.removeImages.setToolTip(QtGui.QApplication.translate("GhastlyLion", "Убрать файлы", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("GhastlyLion", "Инструменты", None, QtGui.QApplication.UnicodeUTF8))
        self.save.setToolTip(QtGui.QApplication.translate("GhastlyLion", "Сохранить полигоны", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("GhastlyLion", "Тип", None, QtGui.QApplication.UnicodeUTF8))
        self.type.setItemText(0, QtGui.QApplication.translate("GhastlyLion", "Полигон", None, QtGui.QApplication.UnicodeUTF8))
        self.type.setItemText(1, QtGui.QApplication.translate("GhastlyLion", "Прямоугольник", None, QtGui.QApplication.UnicodeUTF8))
        self.type.setItemText(2, QtGui.QApplication.translate("GhastlyLion", "Круг", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("GhastlyLion", "Физические формы", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
